name: setup-pixi
description: Install the pixi package manager
author: Pavel Zwerschke
branding:
  icon: package
  color: yellow

inputs:
  pixi-version:
    description: Version of pixi to install
  pixi-url:
    description: URL of pixi to install
  log-level:
    description: |
      Log level for the pixi CLI.
      One of `q`, `default`, `v`, `vv`, or `vvv`.
  manifest-path:
    description: Path to the manifest file (i.e., `pixi.toml`) to use for the pixi CLI. Defaults to `pixi.toml`.
  run-install:
    description: Whether to run `pixi install` after setting up the environment. Defaults to `true`.
  environments:
    description: |
      A space-separated list of environments to install. If not specified, only the default environment is installed.
  locked:
    description: Whether to use `pixi install --locked`. Defaults to `true` when the lockfile is present, otherwise `false`.
  frozen:
    description: Whether to use `pixi install --frozen`. Defaults to `false`.
  cache:
    description: Whether to cache the pixi environment. Defaults to `true`. Only works if `pixi.lock` is present.
  cache-key:
    description: |
      Cache key prefix to use for caching the pixi environment.
      Defaults to `pixi-`. The full cache key is `<cache-key><conda-arch>-<sha-256-of-pixi-lock>`.
  cache-write:
    description: |
      Whether to write to the cache or only read from it. Defaults to `true`.
  pixi-bin-path:
    description: |
      Path to the pixi binary to use. Defaults to `~/.pixi/bin/pixi`.
  auth-host:
    description: |
      Host to use for authentication. If not set, pixi is not authenticating.
      Requires `auth-token` or `auth-conda-token` or `auth-username` and `auth-password` to be set.
      See https://prefix.dev/docs/pixi/authentication
  auth-token:
    description: Token to use for authentication.
  auth-username:
    description: Username to use for authentication.
  auth-password:
    description: Password to use for authentication.
  auth-conda-token:
    description: Conda token to use for authentication.
  post-cleanup:
    description: |
      If the action should clean up after itself. Defaults to `true`.
      If `true`, the pixi environment, the pixi binary and the rattler files in ~/.rattler and ~/.cache/rattler are removed.

runs:
  using: node20
  main: dist/index.js
  post: dist/post.js
