name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

# Automatically stop old builds on the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  default:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
        cache: [true, false]
    runs-on: ${{ matrix.os }}
    name: default ${{ matrix.cache == true && 'with' || 'without' }} cache (${{ matrix.os }})
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Move pixi.toml
        run: mv test/default/* .
      - uses: ./
        # check the action logs to see if the cache was used or not
        with:
          cache: ${{ matrix.cache }}
      - run: |
          set -o pipefail
          pixi info
          test -f .pixi/envs/default/bin/python
          ./.pixi/envs/default/bin/python --version | grep -q 3.11
        shell: bash
        if: matrix.os != 'windows-latest'
      - run: |
          set -o pipefail
          pixi info
          test -f .pixi/envs/default/python.exe
          ./.pixi/envs/default/python.exe --version | grep -q 3.11
        shell: bash
        if: matrix.os == 'windows-latest'
      - run: |
          pixi run python --version | grep -q 3.11
          pixi run test | grep -q "Hello world"

  pyproject:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Move pixi files
        run: mv test/pyproject-manifest/* .
      - uses: ./
        with:
          pixi-version: v0.41.3
      - run: test -f .pixi/envs/default/bin/python
      - run: pixi run test
